### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by FudgeDumbo** [Roundaround/mc-fabric-villager-converting#2]
it crashes on loading.

**Comment by Roundaround** [comment]
I'm going to need more information than that. What is it saying?

**Comment by FudgeDumbo** [comment]
not much just says error code :1 if I try with client side
even tried on server to see the logs on console
it just crashes 
fabric loader 0.14.7 with nothing but villager covert mod

**Comment by FudgeDumbo** [comment]
oh and the minecraft version 1.19 of course with 1.0.0+1.19

**Comment by loadingspace** [comment]
[latest.log](https://github.com/Roundaround/mc-fabric-villager-converting/files/8880726/latest.log)
I'm also having the issue that it just crashes. At a certain moment it gives `[main/ERROR]: Mixin apply for mod villagerconverting failed` followed by an error I don't understand.  After that it just crashes. I didn't do more in depth testing, but I removed the mod, and now it does run.

**Comment by FudgeDumbo** [comment]
like i mentioned there is no crash report at all. it fails to load during preparing session and does not create crash report

**Comment by Roundaround** [comment]
Okay I've pushed v1.0.1. Hopefully it should resolve the issue. Please let me know how it works!

https://modrinth.com/mod/roundaround-villager-converting/version/1.0.1

**Comment by loadingspace** [comment]
Hey, I don't know if what the etiquette is replying to closed issues, but this fixed it, so thank you so much!

**Comment by FudgeDumbo** [comment]
you are awesome. I was not sure how to support you to fix the issue~

thank you very much!
________________________________
보낸 사람: loadingspace ***@***.***>
보낸 날짜: 2022년 6월 11일 토요일 오후 1:35
받는 사람: Roundaround/mc-fabric-villager-converting ***@***.***>
참조: FudgeDumbo ***@***.***>; Author ***@***.***>
제목: Re: [Roundaround/mc-fabric-villager-converting] crashes (Issue #2)


Hey, I don't know if what the etiquette is replying to closed issues, but this fixed it, so thank you so much!
